// export const VALID_PARAMS = {

//     ISI HASIL JSON SCHEMA DARI JsonSchema.net
//      YANG SELANJUTNYA VALIDASI BISA DIPASANGKAN DI BAWAH ASSERT EQUAL 
//      DENGAN IMPORT FILE INI TERLEBIH DAHULU
// }